# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-10-09 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['order'], 'verbose_name_plural': 'Menu Items'},
        ),
        migrations.AddField(
            model_name='menuitem',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
