# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-10-09 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20231009_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
