# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-16 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0019_auto_20150316_0231'),
    ]

    operations = [

        migrations.AlterField(
            model_name='article',
            name='blurb',
            field=models.TextField(blank=True, help_text=b"For blog posts, the blurb will show up on the\n                                                 search and 'recent' page. No &lt;p&gt; tags..."),
        ),
        migrations.RemoveField(
            model_name='genre',
            name='articles',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='articles',
        ),
        migrations.AlterField(
            model_name='article',
            name='genre',
            field=models.ManyToManyField(blank=True, db_table=b'article_genre_articles', related_name='articles', to='article.Genre'),
        ),
        migrations.AlterField(
            model_name='article',
            name='labels',
            field=models.ManyToManyField(blank=True, db_table=b'article_tags_articles', related_name='articles', to='article.Tags'),
        ),
    ]
