# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-01-27 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0020_auto_20180116_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='search_title',
            field=models.CharField(blank=True, max_length=765, null=True),
        ),
    ]
