# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-01-27 21:40
from __future__ import unicode_literals

from django.db import migrations

import utility

def create_searchable_title(apps, schema_editor):
    Article = apps.get_model('article', 'Article')
    for obj in Article.objects.all():
        obj.search_title = utility.make_sortable(obj.title)
        obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('article', '0021_article_search_title'),
    ]

    operations = [
        migrations.RunPython(create_searchable_title)
    ]
