# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-27 20:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailbag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailbag',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name=b'date'),
        ),
    ]
